### ISSUE TITLE
Best way to handle stringsAsFactors = TRUE in R scripts?

### ISSUE THREAD

**Issue by antoniojbt** [EpiCompBio/genotype_QC_lite#2]
The well known problem (!): 
R reads strings as factors and internally converts them to levels. For an explanation and history see:
https://simplystatistics.org/2015/07/24/stringsasfactors-an-unauthorized-biography/

This is because stringsAsFactors = TRUE is the default in most functions such as read.table, read.csv, data.frame, as.data.frame, read.file. (Does read_tsv do the same?)

data.frame functions will re-convert the object (as it's being coerced) and their default is also TRUE. cbind and rbind will also read strings as factors

data.table fread has stringsAsFactors = FALSE as default however.

The problem is that if the variable is read as a factor, it will generate levels for each (which are numeric, so that regressions can be run, storage is smaller, etc.) and any rows with repeated characters will be converted to the level and internally processed as such.

This is fine as usually columns that are e.g. male/female need to be recoded to 0/1. The coercing to levels is an internal event though and shouldn't be printed to file for instance. Indexing is also preserved.

In some instances this can cause silent bugs, e.g. in the IBD file processing which originally had R's defaults:
[https://github.com/EpiCompBio/genotype_QC_lite/blob/master/aw_imiss-vs-het.R](url)
(now corrected)

The questions is how to best handle this? 
An option is to change the global defaults with:

`options(stringsAsFactors = FALSE)`

Plus some defensive programming with assert statements where new data / inputs are expected to be handled. This can have other consequences though.

Any thoughts @davidmosen and @gh155?

**Comment by davidmosen** [comment]
Thanks Antonio, this is a great overview of the problem.

I would not be exagerating if I say that 20-40% of my most head-scratching bugs and problems have arisen from this in the past. I'm therefore usually over-paranoid and convert everything with `as.character(x)` or with `as.numeric(as.character(x))` just in case. Using the `options(stringsAsFactors = FALSE)` is a really good idea.

**Comment by antoniojbt** [comment]
Depending on others' thoughts I guess we can systematically use:

- `options(stringsAsFactors = FALSE)`
- Plus a test/assert function to compare against the expected input (of columns, rows and variable types possibly), particularly for files reading the initial raw/original data.
- and each analyst can integrate the `as.character(x)` and `as.numeric(as.character(x))` as best practice in their code.

Any further thoughts let me know.
Antonio

**Comment by davidmosen** [comment]
Agreed.
